### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by razerduy** [zbtang/React-Native-TextInputLayout#7]
![screen shot 2017-11-26 at 7 36 57 pm](https://user-images.githubusercontent.com/11910653/33240024-4dfc67ba-d2e1-11e7-943c-7a496902afc6.png)

**Comment by gyanani-harish** [comment]
same issue with me too

**Comment by Ajith-Pandian** [comment]
@razerduy @gyanani-harish The problem is with 'PropTypes'. Before it was part of React. Now it is removed. Instead of **React.PropTypes** this package should use **PropType**s from 'prop-types'.

WorkAround:
1. Install 'prop-types' package by `npm install 'prop-types' --save`
2. Open ` rn-textinputlayout` folder under `node_modules`.
3. Navigate to `rn-textinputlayout/src/TextInputLayout.js`
4. Add following line at the top.
    `import PropTypes from "prop-types";` 
5. Change 'React.PropTypes' to 'PropTypes'

Before:

![BeforeScreenShot](https://user-images.githubusercontent.com/20264665/33760202-e607699a-dc2a-11e7-82c1-ac1650e2bece.png)

After:

![AfterScreenShot](https://user-images.githubusercontent.com/20264665/33760232-0416269c-dc2b-11e7-842f-32091b0c4e9b.png)

I've checked this. It's working for me. I hope this will help you.

**NOTE**: You need to repeat these steps whenever you do `npm install` to install all npm packages.

**Comment by Ajith-Pandian** [comment]
@zbtang Can you add "prop-types" module to remove this error?

**Comment by zbtang** [comment]
This issue has been fixed at version '1.0.5'.
